.TH GPAINT 1X "June 7, 2001"

.SH NAME
gsensors \- a GNOME2 applet to monitor hardware sensors

.SH SYNOPSIS
gsensors [options]...

.SH DESCRIPTION

 GNOME-Sensors (gsensors) is an applet to allow you to easely access and
log the status of your hardware sensors (Temperature, Voltage, Fan ...).
It docks into GNOME2 panel and can scroll the sensors you choose to display.

.SH FEATURES
 + Configurable refresh rate
 + Warning limits
 + Configurable applet display
 + BEEP!
 + Nice logging facility
     
.SH TODO
 + Better look
 + A good detection and module loading system.

.SH BUGS
For bugs or general comments you can send mail to the developer <linux@vkcorp.org>.

.SH SEE-ALSO
\fB X (1), gnome (1)\fP

.SH AUTHOR
This manual page was written by Vinicius Kursancew <linux@vkcorp.org>,
the upstream developer of the program.
