#ifndef __LOGO_H
#define __LOGO_H
/* XPM */
static char *gui_xpm[] = {
/* columns rows colors chars-per-pixel */
"128 112 5 1",
"  c #111111",
". c #666666",
"X c #AAAAAA",
"o c #EEEEEE",
"O c None",
/* pixels */
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooXoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooXXooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXoooooooooXXXXoXooooooooooo",
"ooooooooooooooXXXXXXoXoXoXXXXXXoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXoXooooXXXXXXX.XXXXoXooooo",
"oooooooooooooX.X....XXX.XX.X.XoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXXXXX.X...X....XXXoooooo",
"ooooooooooooXX.............o..oooooooooooooooooooooooooooooooooXoooooooooooooooooooooooooooooooooooooooo.XXXXX.........XXXXooooo",
"ooooooooXXX.X..  . .......XXX.XoooooooooooooooooooXoXXXoXooXXooooooooooooooooooooooXooXooXoXoXoooooooooXoXX.... . . .....XXXoooo",
"ooooooXXX..X.. .    . .  .o...XXoooXooooooooXooooooX.XXXXXoXXXXXXXXXooooooooXoXooooXXoXXXXXoXXXXoooXoooooooX.  ..   .  ...XXXooo",
"ooooXXX........          .XX..XXoooooooXXXoooXXooXoXXXoX..XXX.X.XXXXoooooooXoooXooXoXooXXXX.XXoXXoooXooooooo...   .. . ....XXooo",
"oooooXX........            XX.Xo.XooXXooXXXXooXXooXXXXXXXX..oX.XXoXXXooXooooXXXoXXXXXXXXXXXXX.XXoXoooXooooooX.         .....Xooo",
"ooooXX.X.....  ..          oXoXXoXXXXXXooXXXXXoX.Xo.XXXXXXXXXo.XXXXXXXXooXXoXoXoXXXXXXXXXXXX.X.XoXXXoXXXoooXoX.          ...Xooo",
"oooooX... ..              .XoXXoXXXXo..XXo.XXoXoXXXXoXoXXoXX.ooXXXXXXXXXXXXXXXXXXXXXooXXXoXoX.XXXXXXoX.XXXXoXXXX       . ...XXoo",
"oooooXX..  .  .        X.X.XoXXoXXoXXXXXXXXXXXXXXX.XooXoXooXo.ooXXX.X.XXX.XXXXoXXXoXXooXXooXoXXXXXXoXXXXXXXXXooXX    .   ...XXoo",
"oooooXX..    .        XXXXoXXXoXXo.o.XoXX.XoX.XXXXXX.XXXoXooXXXooXXXXXXXXX.oXXXXXoXX.oXooXooXoXXoXXXXXX.XXXoXXooXX      ....XXoo",
"oooooX...            .XXXXXoXXoXXooXXXXoXXXooXXooXXXXXooXXXX.oXXoXXXoXXXXoXXXoXXXoXXX.XXoXXXXX.oXX.XoX.XXo.oooXXoXX. .   ...XXXo",
"ooooXX..            .XXXXXoXoXXooXoXXoXXXXXXoo.XooXXXXXooX.Xo.oXXo.oXXooXXXoXXXXoXo..  ..ooX.XoXXX.oXoXXoXoXoooXooXo.     ...XXo",
"ooooXX.           .  .XXoXooooXXXXXoo.oXooXX.oXXXoXXoXoXoXXXooXoXXoooXXoXooXXXXXoXXX   .XXXXoXooXoXXoXoXXXooXoooXooXX.     ...XX",
"ooooXX..         .X.  XoXoXoXXoXo.oXooooXooXX.oo.XoXoXoXXo.oXooXooXXXXXooXoXXoXXXXXX    XooXoXXoXooXooXoXooXoXXooXooXX.   ...XXo",
"oooXXX.. .        X..XXXXoXXoXooXXXoXXoXoXXoXXXooXXooXXXXXoXXXooXXXoXoXXXoXXXooXooXX.  ..XoXXXoXoXoo.ooXoXooooXXoXXoXXX. .....Xo",
"ooooX..            XXXoooXXXXooooXXXoXXXXoXXXo.ooXXXoo.XooXoXoXoooo.XooXoXoXXXooXXXo.XXXoXXoX.ooXoXooXXoooXooXoXXooXXX.oX ....Xo",
"ooooXX...       o   XoXooXXoXXoXoX.XXo.XoXo.Xoo.XoXXXXoXXoooooXXooXXoXooXXooXo.XoXXoXXoXXoXXooXXXXoXooXooXXXooXo.XooXX.XX...XXoo",
"oooXX..         XX XoooXoXXooXXo.XXoXooXooXo.XoX.oooXXooXXoXXooXXXXXoo.ooXXoXXooooXoXXXoXXooXooXoX.XXXo.XoXX.ooXooXXXXXXoXXXXoXo",
"ooooX...         .XXooXoXoo.oXXXX.Xoo.oo.ooX.oXoXXooXXXooXoXXo.oXXXXXoXXooXXooXooXXXooXXo.ooXXoo.X  .XoX.oX.oXooXooXXXXXXooooooo",
"oooXXX..         .ooXoXXXXooXoooXXXXXo.oo.ooXoXooooXoXX.ooXXX.oXXXoXoXooXXXXoooXoXoXXooXXoXooXXX.    .XXX.ooXoXX.XXoX.XXXooooooo",
"ooooX.. .  .Xo  .oooXXooXXXXo.ooXoXX.ooXoo.ooXoXoXoXXXXXXXoXooXXooXoX..XoXoXoXoXXXoooXoXXoXXXXoXX    .XXXXoXoX.XX.XooX.XoXoooooo",
"ooooX...  .XXoX.XXXoXoXooX.XoXXXoXoXoXooXoXXooXoXoXoXXXXoXoo.ooXoXX.    XoXoXXXo.oXooXXoXooXXXXoo. ..X.oXooXXXoXoX.XoXX.Xooooooo",
"ooooXX... .Xo.XXXoXXooXXoooXXoXXXXoXXo.oo.oXXoXXoXXXXoXXoo.ooXoXXoX.    .o.oXXoX.XXXooXXoXXoXX.ooX.XXXX.oXooXXooooXXXoo.XXoXoooo",
"oooooXX.. ..XX.XoXoXoooXXXXoXXoX.XooXoX.XXXooXX.ooXXXooXXoXXoo.oXoX.    ..oXoXXooXXoXooXXoXooXoXXoXXXXXo.XoXXoXoXooXXXX.XXoooooo",
"oooooXX....X.ooXooXXoXXoXXXXoXooXXoooXoX.oXooXXoXooXXXooXXXoXooXoXX.    .XXXooXXoooXoXooXXoXooooXoXXXooooXooXXo.ooXoXX.XXooooooo",
"ooooooXX...XXXXoXooXXoXXXXXXXoXXXX.XoXoXoXXoooXooXooXXXXoX.XoXoo.oX.     X.XoooXXXXoXXXoXoXoXoXXXoXXoXooXo.ooXoo.ooXoX.oXXoooooo",
"oooooXXX.XX.XoXXo.XooXoXXoXoXooXoXXXXXXXooXXXXoXooXXXoXXoo.oXXXooXX.     .oX.XooXXXXXXoXXo.oXXXXooXoXoXoXXXXXXXXXXooXo..oXoooooo",
"oooooXXXo.Xo.XoXoX.ooXXXoXo.o.oXXXXXoXoXooXXXoooXXoXXooX.oXXXooXooX.     .oo.XXXooXXXXXooXXXoXXXXooXoXoXX.oXXoooooXX.X..Xooooooo",
"ooooooXoXX.XoXXXXXXXooXoXoXo..XXXXXXXoooXXoXoXXoXoooXXooXXooXXXXXXXo      XooXXXoXXooXoXoXXXXoXoXXooXXXoXXXXoXXooXX.X.XX.ooooooo",
"ooooooooXXXXooXXoXooXXXooXXXoXXXXXXX.oXoXXXXooXXXooXoXXoXoXooXXXo.Xo.     .XooXXXXXXooXX.XoX.ooXoXooXoXXX.oXXoXXoXoXoo.XoXoooooo",
"ooooooooXX.oXXoXXoXXX.oXoXXXXX..XXXXXXXXooXoXooXo.oXo.XXXXoXooXoXXXXo      X.oooXXoXXooXXoXooXoooXXXX.XXXXooXXXXXooXXXo.ooXooooo",
"oooooooXoXX.X.ooXXoXooXoXoXoXXX..XX.XXXooXoXX.ooXXXoXoXXooXoXo.XoXoXX.      XXooXXoXXXooXoXXooXooXXooXXooXXooXooXXooXXXX.ooooooo",
"ooooooXoXXXXXoXooXooXXo.XXooX.X  ......XXXoo.XXooXXXooX.XXoXX.XoXoXXXX.       XXXXXXoXXooXoX.oo.ooX.XoXXoXXXoXooXXXoXXoXoXoooooo",
"ooooXooooXXoXXXXooXXoXXoXoXXXX... .   .oXoXoo.oXoo.XXooXXoXoXoXoXoo.XX.       ..XoXXooXooXXooXoo.oXXXooXXoXXooXoXX.Xo.XXXoXooooo",
"oooooooXXXXXo.oXXXXXoo.oX.XXX..X..   ..XoXX.ooXoXoXXXXXXXooX.oo.oXoo...        .oXoXXoXXXX.XXoXooXoXXXooXooXXXXXooXXXo.XXXoooooo",
"ooooooooX.X.XXooX.XXoooXoo.X.......   ..XooX.ooXo.ooXXXoXXoXo.oX.oXoo.X.        XoXoXXooXXXXooo.XXXXXXXXX.oooXoXXoXX.XXXXooooooo",
"oooooooXX..XXXXXooXo.Xo.XX. .......... ..XooXXooXoXooXXooXXooXXooXoXooXo..       .XXXXXoX.XXXo.  ..XXXXXoXXXoXXXXXXoX.XXXXoooooo",
"oooooooXXXXXXoXXooXooXXo.o.. ....... .   ..XXXXXXXoXooXXooXXooXXoo.oXXoXX..         . .  .  .      XXoXXXooXoo.XoXXXoXXXXooooooo",
"oooooooooXXXXooXXXoXoXXooXX..... ......  ..XoXXXoXXoXoXX.ooXXooXXXo.XXoXXX.                        .oXo.ooXXXXooXXXXooXX.ooooooo",
"oooooooXXXXXXXooXoXo.oX.oo.XX..  ..X.... ..X.XXoXo.XX.ooXXoXXXoXo.XXoo.XXXo.                       .XoXX.oXXo.oXoXooXXXXXXoooooo",
"ooooooooXXXXXoXooXoXXXXX.ooXXX... ....... . .oXXXXo.XXXooXXooX.oXoXXooXXXooX.                      .XXoXXXooXX..oXooXXXoXooooooo",
"oooooooXXXXXXXoXooXX..XXX.Xo.X.........XX... XoXXXooXXXXooXXooXXooXXXooX.ooXX...                  .o.XooXXXooXooXoXXXX.XoXoooooo",
"ooooooooXXXXoXXXXooXoX..X..o.XX.... ....oXX.XXXooXXoo.ooXXoXXooXoXoXXXooXXXoXoX..  . .  .. .   . ..XoXXooXo.oXooX.oooXXXXooooooo",
"ooooooooo.oXXXXXXXo.oo..XX..XXXX..X. ....o...XXXooXXooXXXXoXoXXXXXooXoXooX.ooXoXXXXXXoo.XXoo.oXX.oXXoo.XooXXXXXXoXXoXXoXXXXooooo",
"oooooooXXX.oXooX.XXoXXX....... .X..X......XXX.X.XooX.ooXXo.XoXXoXXoXoXXXooXXooX.oXooXXoXXXXooXooXXoXXoo.XoXXoX.XooXXXXoXXXoooooo",
"ooooooooXX.XXoXoXXXoo......... ..X.... ...XoXXXo.XooXXoo.ooXXooX.ooXooXXXooXXooXXooXoXXooXXooooooXXoX.oo.Xo.ooXXXooXXXXXXXoooooo",
"ooooooXoX.XXoXXXoX..X.X...XXX...  ..XX..XX.XXX.ooXoooXXXXXXoXoooXXooXoooXXoo.XoXXXooXoXoooXXXo.XoX.ooXXooXXoXooXXXooXXX.Xooooooo",
"ooooooooXX.XooX......X......oXX..  X.XXXXX.oXoXXooXXoXX.ooXXoXXoXXXooXXoXXXXXXXooXXXXXoXXXoXXXo.ooXXXoXXoo.ooXoXXXXXX.XXXooooooo",
"oooooooXoXoXXXoX....X....XX..XX.X.  XXXX.XXXXoo.XooXXXXXXooXXoXXoXoXooXXXXXXooXXXXoXoXXoXXXooXo.Xoo.oXoXXoo.oXXooXXXXoXXXXoooooo",
"ooooooooXXXoXXooX. ..X....XXXXXX... XoX.XXXXXXooXXooXXXXXXooXooXX.ooXooXXooXoooXXXoXXXoXXXXXXoXoXXoXXoXoXXoXXoXoXoXoXXXXXooooooo",
"oooooooXXXXXXXXoX..   . ...X..XXo...Xooo.XXXXXXooXXoXXoXoXXooXoXXoXo.oXoXXooXXooXX.XoXooXXoXoXoXXXoo.ooXXXXooXoooooXoXXXXXoooooo",
"oooooooXo.ooXXXXXX..    ....X.XXXX....ooo.XXXXXXooXXo.XoXoXXooXXXoXooXo.XXXooXXo.XXXXoXXoXooXoXooo.ooXoo.oXoooXXoXXooXXXXooooooo",
"ooooooooXXXXXXoXXX.X.    .....XX.X...X.Xoo.X.XXoXXoXXXXooXoXXX.ooXoXXoooXXXXo.oXoXX.XoXXoXXooXoXooXXoo.oXXo.XoXXoooXoXXXXooooooo",
"ooooooooXXX.oo.XoXXX...   ....XXX.....X.XooXXXoXo.oXXoXoooXoXXXooXXoXXooXXX.XoXXX.XXX.XXXXoXXoXoXooXXooXoo.o.XooXoXoXoXXXooooooo",
"ooooooooXXoX.oXXXoX..X   .  ..XXX ..X..XXXoXXXoXoX.ooXooXooXXoo.XooXoXooXXXXXoo.XoXXXXXXXXXoXooXo.XoXXooXo.XoXXooXoXo.XXXXoXoooo",
"oooooooooXXoX.XX.oXXo. ..   . ..X......X.XXXoXXoXXoXooXoXXo.oXXoXXoXXoXXooooXXoo.oo.XX..X..X.XXoXo.ooX.XXXoXoooXXoX.X.XXoXoooooo",
"ooooooooooXoXX.XX.oXXo.....  . ...XXX...XXoXXXXooXXXXooXooXoXoXooX.ooXo.XooXo.XXo.oo.............oXXooX.ooXoXXXoXoX.XoXXXoXooooo",
"oooooooooooXXoX.XXXXX......     .XXXo.XoX.oX.oo.ooXXXXooXooXoXoXooXoooXo.oooXXoXXXXo.X.... .....o.ooXXXXXooXo.oXoXXoXXXXXooooooo",
"ooooooooXXoXXXoX.XX.XoX..........XXoXo.ooXXooXooXooXXXXoXXXoXX.XXoXoXooXXXXo.ooXXXX..X.   . ....oo.ooXXoXXooXo.ooooXXXXXXXoooooo",
"oooooooX. .X.XXXX.XX...XXXX.......XooXo.XoXXXoXooXooXXXXoXXoooXoXXoXXXooXoXXXXooXoXX.X..   .. ...XoXooXooXXX.oXXXXXoXXXXoXXooooo",
"ooooooXXX   XXXXXX.XX..XX.XXX....XXXooXo.ooXoXo.ooXXoXXXXXXoXoXooXXXoXXoXXo.ooXXXXXXX.X....  ...X.ooXXX.ooXXo.oXoXXXXXXXXooooooo",
"oooooooX..   XXXXo......X..XXoo...oXXooXoXooXoXXX.oXXoXXXXXooXXXooXXoooXXoXXXoo.XXoXXX.....  . ..oXXoXXXXoXXooXXXoXoXXXXXXoooooo",
"oooooooX....  .XXXX....XXooXX.oo..XoXXooXo.XooXXooXoXoooXXo.ooXXXooX.oXXoXoXoXX.X.XX.XX..X.X. . .XoXXoX.oXXoXo.XooXXoXXXXXoooooo",
"oooooooX. .X.  ...XX..XXoXooXXXXXXXooXoooXoXXXooXooXoXoooXXoXooXooXoXXooX.oXooXXXX.XXX.X...oX. . .XXXXXoXooXoXX.oXoXXXXXooXooooo",
"oooooooX.. .X   ...XXXXXoXXoXoXXoXoXoXXXXoXoXXXoo.oo.X.Xoo.XoXooXXoXo.XoXoXoXoXXXXX.. .oX.XooX......XXXoo.X.XooXXoXXooXXXXXXoooo",
"oooooooXX .....  ...XX.X.XXXooXXooooXXXXXooXoXXXoo.ooXXXooo.XoXXo.ooX.o.oooX..XXX.X..  .X...XoX.....XXXXXXoX.XooXXXXXoXXXXoooooo",
"ooooooXX........  . .XXXXXoXXooX.XXXXXoXXXXoXoXoXooXooXoXXooXXoXX.XooXXXXXoo.X.XX.XX.....XXX.oXX. ....XoXooooXXoo.XoXXXXXXXooooo",
"oooooooXX......X..  X.XXXXXooXooX.oXooXXoXoXoXXoo.XXXoo.oXXoXXXo.XoXooXXoXXoo.X.XX....  ...o.XoXX......XoooXooXXoXXXX.XXXXXooooo",
"ooooooXoX.. ............oXXXoXXoXoXooooXXXooooXXXoXXXXo.Xo.oXXXXXoXoXooXXXXXoX.............XoXooX..o...XoXXXXoXoXXo.XXXXoooXoooo",
"oooooooXo.  ........... XoXXXXXX.XXXoXXo.o.oXXoXXooXXX.ooXoXXoXoXXoXooXoX.oX.Xo...X. ...  ..XXXoo.XXX..oXXoXoXooXoooXX.XXXoXXooo",
"oooooooXoX.  X.  .. .....ooXoXXXoXooXo.XXooXoooXoXooXXXXooXoXooXoXoXXooXXoXXX.X.......XX.....XoXoooXXXXXoXXoXXXooXoXo.XXXXoXXXoo",
"oooooooo.X.. .  .... .....ooXoXXXoXoXXoXoXXoXooXXXXooXoXXooXoXXoXXXXoXXXXoX.Xo.. .  ..........XoXoooXXXXXX.oXXoXXoXoXoXX .XX.Xoo",
"oooooooo... ....XXoXX......ooXXXoXoXooXoooXoo.ooXXX.oXXXoXooXXXXXooXXXXXX.X..X. .  .  . .......Xo.XoXXoXXXoXXXX.oX.oXXo.....XXoo",
"ooooooooX....  XXXoo.X...XXXooXXooXoXoXoXooXXo.o.XXo.ooX.oXoo.XXXXoXoXXXX......X.     ..........X.XoXooXXXooXoXXoXXXo.......XXoo",
"oooooooXXX..X...oXXoXXX.X.XoXXoXXoXXXXoXXXXoXooXoXXoo.XoXXoXooXoXXXoooXXXXX..X..X.X...   .XXo..X.Xo..ooXXXXXXXXXXooXX   . ...Xoo",
"oooooooooXX..oX.oXXXooX.XoXXXoXXXXoooXXo.oooo.oXXo.ooo.XooXoXoXXoX.XoXoXXXX......X.....  ...oo.oX.ooXXooXoXXoXXoXXooX      .XXoo",
"ooooooooXXXoXXX..oXXXooXoooXXo.oXXXooXX.XXoXooXoXXoXooXXooXXoXXXoXXXoXXoXXX  .X.XXX..........XX.XoXooXXoXoXXooXooXXoo.    ..XXoo",
"ooooooXoXoXooXXX.XoXXXooXoXooXXoXoXXooXXXXXoXoXXooooXoXX.ooXXXoXXXoXXooXoXX  XXXXXXX.........XoX.ooXooXXXooXXXXXoXX.oX    ..XXoo",
"oooooooXX.XXXXXXXXXooXXX.ooooXXooXoXXXXoXXoXoXXX.oXoXXoooXXXoXooXXooX.ooXo.. XX.X..X... ......ooX.ooXXXXXXoXXXooXX. .X    ..XXoo",
"oooooooXXXXoXoXoXoXXoXXX.oooXXoXooXXXXXXoXXoXXXoXXoXo.XooXXXooXooXXXXXXoXX....X..XX...X..o.oX..ooXXXoXXXXoXoooXoo.         .Xooo",
"ooooooooXX..oXooXXXXXo.XoXoooXoo.ooXXooXXo.XooXoXX.XXooXooXXX.XXooXoX.oXoX.. .X.X...X....Xo.XXoXooXXXXXo.ooXooXXXX        ...Xoo",
"oooooooooXXXXXXXoXXXXoXXooXXXX.ooXooXXXoXXXooXoXoo.XXoooXo..XoooXooooXXoXo.......X..X...X.oX.XoXXooX.ooXo.ooXoo. X.      ...XXoo",
"oooooooXXXXXXXXXXoo.Xoo.XoXXooXXooXooXXooXooXooXXooXXXXoXXoXXooXX.oXXoX.XX...........X...X.oo.XoXXoXXXXooo.ooXo   .       ..XXoo",
"oooooooXoXXXXXXXX.oo.XooXXooooXoXooXoXXXooXoXooXoXoo.XoXXooXXXooXXXoXooXXoo..... .  ..o...X.Xo.XoXXXXXXoXXoXoo..          ..Xooo",
"oooooooXX..XoXXoooXooXooooXXXoXooXXo.ooXXXXXo.ooXoXooXXoXooXXXXoooXXoooooXooXXX... ..XXX..oXXooXXXXoXXoXXoooX...         . ..Xoo",
"oooXooooXoX.oooXXoo.XoXoooXoXXoXXoXXXXooXXoXXXXooXXXoo.XooXoXXXXooXX.oXXXXXoXoXoX.X..X.XX.oXXXXoXoXooXooXooXo.  .         ..XXoo",
"oooooooXXXXXXooXXXoo.ooXoooooXXoXoo.oXXooXXXXXoXoooXXooXXoXXXXoXXooXo.oXXXoXXXXoXXXoXXXXoX.ooX.ooXXXoXXooXoXX.           ...XXoo",
"ooooooooXXXXXXoX.XXoXXooXoo.oXXXoXooXooXooXXXXooXooXXXooXoXX.XoXXXXXXoXooXooXoXXXoXXoXXXooo.ooXXooXXXoo.ooX.              ..XXoo",
"ooooooXXXoXXoXXoXXXXooXoXooooooXXoXXo.ooXXXXXoXXoXoXoXXooXXooXXoXoXXXXXXoXXXooXXoXXXXo.XXXXX.oooXooXoXooXXo.              ...Xoo",
"ooooXX..XXXXXoXXooXXXoo.XoooXXooX.oXXXXoXXXoXooXoXXooXXXooXXooXoo.oXooooXo.oXXXooooo.XoXXXXo.XooXXXXoXXoX.XX             ....Xoo",
"ooooX... XXX.XoXXoXXXXoXXoXXoXXoXXXo.oXXXXXXooooooXXoXoXXXXoXXXXXo.oXoXooXoXoXXXXXXXoXooX.XXoXXX.oXoXXXXX. .               ..Xoo",
"oooXX..   X.o.oXXXX.oXXoXooXXoXXo.oXoXoXXXooXoXooooXooooo.oXoXooXooXoXXXXoX.XooXXoooXXXoooXXXoX.XooXoX.X..                 ..XXo",
"oooXX....  .oo.XoX.XooXXXooXXooXXoXXooXXoXooXXoXooXoXooXXoXoooXooXoXXoXXXX.ooXXoXXXoXXooXoX.XoXoXoXoXoo. .                 ...Xo",
"oooX...     ..XXXXXo.XoXXXooXXoo.ooXXooXoo.ooXXoXooooXooXooXoXoXXoXXoXoXoXXXooXoXXXXooXXXXXoo.Xoo.oooXoX                    .XXo",
"ooooX...     .XXXXXoooX.oXXoXXXooXoo.XooXXoXooXXXXooooXooXoXXXXXXXXXXXXXooX.Xoo.oXXXXXXoXXXoooXXoXXXooXX                    .XXo",
"oooXX....     .XXXoXXoXXoXoXooXXooXooXXooXXoXXoXXoXooXXXooXoXXXXoX.oXXXXXXoXX.oXXoXoXo.oXXooooXXXoXXXXo.                    ..Xo",
"ooooX.... .     XXXo.XoX.oXXXoX.XoX.XXXXXoX.oXXXXXXXX.ooXoXX.o.XXoX.XoXoX.XXXXXoXXXXoXo.Xo.oXXoXXoX. X..                  ...Xoo",
"oooXXX...        . Xo.XXo.oXXXo.X.XX.X.XXXX.XXXX.oXX.XXXXXo.o.XXXXXXXXXXo.XXoXX.oXXXoXXXXXo.X.XXX.XX  .                  ...XXoo",
"ooooX......        .XXXXoo.XooXXXXXXX.XXXXXXXXXXXX.XXXXXXoXXooXXX.Xo.XXXXXXXXXX.XX.XXXoXoXoo.o.XXo...                   . ..XXoo",
"ooooXX.....          XXXXXX.XoXoXXXXoXXXXXXXoXXoXXXXXXoXXooXXoXXXXXooXXoXXoX.XXXXXX.X.ooXo.XXXooXX...                  . ...XXoo",
"ooooXXX...... . . .  .ooXXoXXXXoXXXoXoooXXoXXXoXXXXXoXooXXXoXooXXoXXoXXooXoooXXoXXXoXXXXXXX.oXXoX.X..  .       .     .  ..XXoooo",
"oooooXX.......... . ...ooXXoXXXXoooXooooooooooooXoXooooooXoooooooXooooXXooooooooooXoXXX.XXX.XooXXX...  .. ... . .. .......XXoooo",
"ooooXXXXX..............XooooooXoooooooXooooooooooooooooooooooooooooooooooooooooXoooooXXX.XXXXXoo.X........ . ... ........XXooooo",
"ooooooXXXXXXXXX.XX.XXXX.ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXoXXXXXooooooX....................X.XXoooooo",
"oooooooXXXXXXXXXXXXXXXXXXoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.XX.XX.........XXXXXXXXXXoooooo",
"ooooooXooXoooooooooooooooXooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXXXXXXXXX.XXXXXXXXoXXXXoooooooo",
"ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooXXooooooooXoXooooooooXoooooooo"
};
#endif
